FROM postgres:14

# Install dependencies and pgvector
RUN apt-get update && apt-get install -y \
    postgresql-server-dev-14 \
    gcc \
    make \
    git \
    && git clone --branch v0.4.2 https://github.com/pgvector/pgvector.git \
    && cd pgvector && make && make install \
    && cd .. && rm -rf pgvector \
    && apt-get remove -y gcc make git postgresql-server-dev-14 && apt-get autoremove -y && apt-get clean

# Set default entrypoint
CMD ["postgres"]