"""Add webhook table with JSON payload

Revision ID: d4215e84a6b8
Revises: f6f6f98afc5d
Create Date: 2025-05-11 20:59:56.562215

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd4215e84a6b8'
down_revision = 'f6f6f98afc5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'webhook',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('event_type', sa.String(), nullable=False),
        sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), 
                 server_default=sa.text("'{}'::jsonb"), nullable=True),
        sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), 
                 server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_event_type'), 'webhook', ['event_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_event_type'), table_name='webhook')
    op.drop_table('webhook')
    # ### end Alembic commands ###